### PR TITLE
Added --protocol=29 for rsync backwards compatibility

### PR DESCRIPTION
**Pull request by biutthapa**
Adds push-files compatibility to Intel Macs.

### CODE REVIEW

**Comment by jacobobryant** [comment]
:+1:  planning to test and merge this soon

**Comment by jacobobryant** [comment]
In reading the docs for `--protocol` in `man rsync`, it looks like this flag is mainly intended for use with the `--write-batch` option. I would've thought that in regular circumstances, `rsync` would negotiate the protocol version with the server automatically, but maybe that isn't the case. So just to double check: if you run something like `rsync README.md app@<your server domain>:README.md`, with and without the `--protocol=29` option, it only works when the `--protocol` option is set, right?

Also out of curiosity can you paste the output of `rsync --version | head -1` both on your local machine and on the server (ec2 right?). I'm wondering if the client or the server has the older version.

**Comment by biutthapa** [comment]
It's when the sender(client) is an older version.
**On the server:** rsync  version 3.2.7  protocol version 31
**On the local machine:** rsync  version 2.6.9  protocol version 29

**Comment by jacobobryant** [comment]
👍 thanks for checking.

**Comment by jacobobryant** [comment]
Just released this. You can upgrade your app's `:dev` alias dependencies to:

```clojure
:extra-deps {com.biffweb/tasks {:git/url "https://github.com/jacobobryant/biff",
                                :git/tag "v1.8.26"
                                :git/sha "1a1eccf"}}
```

**Pull request merged**
